### PR TITLE
Replace some assignment operators with idential operators

### PR DESCRIPTION
**Pull request by C-Lodder**
Performance improvements with operators.

I can continue working on the rest of the files if you wish

**Assignment Operator (`==`):**
xi8w7

**Identialcal Operator (`==`):**
gs1eh

### CODE REVIEW

**Comment by undeflabs** [comment]
I would do not change files which are developed by others, like the files in
`
includes/core/XmlRpc/*
includes/core/gbxdatafetcher.class.php
includes/core/mxinfofetcher.class.php
includes/dedimania/*
includes/maniaexchange/*
includes/musicserver/*
`

Anyway I think that those changes doesn't change the performance much, do you have some benchmarks about this topic?

**Comment by C-Lodder** [comment]
I don't have any benchmarks, but it's a known small performance boost because when matching values, it doesn't do typecasting. Check the screenshots above to see the differences of the checks.

https://stackoverflow.com/questions/2401478/why-is-faster-than-in-php

I can revert the vendor files if need be, but are they ever updated anymore?

**Comment by undeflabs** [comment]
I read https://stackoverflow.com/questions/2401478/why-is-faster-than-in-php and I do believe it is good for performance, but I think that the improvement is not that great for the amount of work. But if you want to do it, keep going.

All of these files are still updated from time to time:
`includes/core/XmlRpc/*`
`includes/core/gbxdatafetcher.class.php`
`includes/core/mxinfofetcher.class.php`
`includes/maniaexchange/*`
`includes/musicserver/*`
So it would be better to revert the changes and keep them untouched.

The whole `dedimania` related files should be rewritten anyway (sometime later).

**Comment by C-Lodder** [comment]
Sure, I'll revert the vendor files and continue working on the rest of the controller tomorrow.

**Comment by C-Lodder** [comment]
@undeflabs files reverted

**Pull request merged**
